### ISSUE TITLE
Option to mark interlocking tree structures of F metatiles in fylfots, as shown in figure 2.12 of the original paper

### ISSUE THREAD

**Issue by nealmcb** [isohedral/hatviz#4]
One of the most interesting and easy-to-track structures that I've run across in your amazing new aperiodic tiling are the interlocking trees of F metatiles in fylfots, joined by a few other metatiles, as shown in figure 2.12 of the original paper.

So along the same lines as my notion in isohedral/hatvalidate/issues/3, I wonder if an option could be added to make those visible in the output of hatviz.

Many thanks.

**Comment by isohedral** [comment]
The up-to-date version of the visualizer here on Github includes colour selectors.  So an easy way to see the tree of F metatiles is to choose a strong colour for the F hats, and white for the other hats.  OK, that's not quite the same as filling in the metatiles themselves, I guess, but it works as a visualization.

If you really want to colour in the metatiles, you can achieve that outside the app. Save the patch as an SVG. Then find the first `<polygon>` with five points (which will correspond to the lowest-level F metatile) and edit its fill.
