### ISSUE TITLE
These larger tile sets are so reminescent of Julia sets

### ISSUE THREAD

**Issue by jerstlouis** [isohedral/hatviz#5]
![juilaSets](https://user-images.githubusercontent.com/5140074/230688605-9d054ef6-ca7d-4cf1-bf89-0ad8d443cf39.png)

![fractals](https://user-images.githubusercontent.com/5140074/230696091-474de987-bf6b-494f-99f6-c3895d03710f.png)

Is there any chance there could be some kind of connection? :)

Am I missing an obvious reason why this would be the case?

The fractal nature of Penrose tiling has been shown before: https://www.researchgate.net/publication/237519315_On_the_fractal_nature_of_Penrose_tiling

I am wondering if there is a supertile organization that would more exactly match a Julia set (and perhaps the different monotiles in the family match Julia sets with other parameters).

Also crazy idea: what if it is a monotile that does not require reflecting tiles that corresponds to a Julia set?

e.g., is this a monotile: (probably not)

![isThisAMonoTile2](https://user-images.githubusercontent.com/5140074/230727434-380c609f-95fd-47d9-b1e4-af8886008bef.png)

maybe this one? (seems to be periodic :()

![orThisOne](https://user-images.githubusercontent.com/5140074/230741889-0d2dff01-6a73-4489-af69-fda70c32dc1a.png)

**Comment by isohedral** [comment]
For future reference, it seems to me that the Github issues section of the visualizer is not the place to discuss the underlying research.  I'm barely a Github user at all, and this will just confuse me.

It seems to me that the fractal structure brought about by the substitution rules given in the paper is partly accidental, and not fundamental to the nature of this tiling, so I wouldn't read too much into it.  That being said, I'm not an expert on tiles with fractal boundaries.  There could be some reason for the visual similarity, but I wouldn't know where to look for it.

Joseph Myers has exhaustively characterized all other polykites up to size 21 and found no other monotiles, so I know without investigating that your two examples either tile periodically, or not at all.

**Comment by jerstlouis** [comment]
Thanks @isohedral and sorry for bringing this up at the wrong place.
