### ISSUE TITLE
Recommendations for p5js to github integration

### ISSUE THREAD

**Issue by jht9629-nyu** [isohedral/hatviz#6]
Hello,

I'm very impressed with this algorithm and I am also exploring the bigger issue of moving between the open world of editor.p5js and more regulated world of github.

Here is a rendering of this code in editor.p5js editor with some minor changes to avoid script warnings:

[03-jht-hatviz](https://editor.p5js.org/jht9629-nyu/sketches/7hzeHDSIl)

I'm not sure why the script waring occur on the calls to createColorPicker, 
they do not occur when running locally via visual studio code using the p5.vscode extension by Sam Lavigne.

I also use the code formatting extension "Prettier - Code formatter", which is odds with editor.p5js formatting defaults which causes some annoying diff changes moving local script editing and editor.p5js

Any suggestions to smooth out this workflow?

FYI: p5js sketch sharing issues come up in my NYU-ITP course:
[IM-Screens-2023](https://github.com/jht9629-nyu/IM-Screens-2023)
which is using my new p5js kit:
[p5VideoKit](https://github.com/jht1493/p5VideoKit)

**Comment by isohedral** [comment]
I think I fixed the script warning.

I don't anything about "Prettier - Code formatter" or p5.vscode, sorry.
