### ISSUE TITLE
Save a text file of tiles, neighbors, etc.

### ISSUE THREAD

**Issue by nealmcb** [isohedral/hatviz#7]
_Feature request_

In addition to the options to save graphical representations (PNG and SVG), it would be great to be able to save the configuration of tiles in an easy-to-parse text file, e.g. csv or json. That would make it easy to analyze the supertiles in other programming environments, etc.

Most any dump of hats including color, orientation and some sort of coordinates or relative positions would be a great start, but here's one format proposal.
For example, if it was a csv dump, it could include these columns:

`id,color,orientation,x,y,neighbors,...
`

I picture orientation being specified relative to the overall grid, where the values 0-5 denote clockwise rotations from the base hat, and 6-11 are flipped horizontally and likewise enumerated clockwise from the flipped base.

We could define a "home vertex" of the hat as the vertex around which the rotation / flipping happens, e.g. the large obtuse angle to the rear of the hat, as used in [hatvalidate](https://github.com/isohedral/hatvalidate).

x and y coords would specify the location of the home vertex, using the hexagonal grid used in hatvalidate, since they are all integers.

Neighbors are either a hat id, or a negative number for the patch edge / unknown. I guess there can be up to at least 6 of them (e.g. for the F_2 hat of the F cluster in Figure 4.1).

Example output, for the basic H metatile (Figure 2.5, where tile 0 is surrounded by tiles 1,2,3 and a bit of the unknown edge (-1):
Some of the coordinate values here may be wrong or are left out, pending a more careful layout on the kite grid, but it's a start.

```
id,color,orientation,x,y,neighbors
0,blue,7,0,0,0,1,-1,2,3
1,light-blue,2,2,2,-1,-1,-1,0,-1
2,light-blue,2,1,1,...
3,light-blue,4,...
```

Of course there might be more natural definition of these values, in keeping with the implementation or theory or formats used in other tiling software. I'm just trying to be concrete about what might be easy to analyze for the case at hand.

A nice alternative color scheme could be dark blue for F tiles (which make a branching river network), dark green for P tiles, light green for H tiles, and white for T tiles.

JSON format is probably more natural for this, but it's harder to generate an example by hand.

**Comment by nealmcb** [comment]
By way of motivation, having this sort of output would make it easier to create a cleaner, more fleshed-out version of this analysis/image of the way that an H supertile (H3 in this case) contains three infinite trees of F metatiles, extending outwards.
![f4-fill-color-trees](https://user-images.githubusercontent.com/119472/231850842-69768c5b-2070-40b4-ae74-494554cb8ccf.png)

**Comment by isohedral** [comment]
Outputting a table containing a listing of individual tile types, positions, and orientations isn't a problem, and I can think about adding that in.

Outputting a table containing topological information (i.e. the IDs of a tile's neighbours) is a *big* problem. There's no clear way to track neighbour information across levels of substitution, based on the code as given. That information can be recovered in principle, but it would require a coding effort well beyond the goals of this small visualizer. (For an intriguing alternative where neighbour information is more readily available, see [Simon Tatham's essay](https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/aperiodic-tilings/).)

Frankly, I think it would be easier to write secondary tools that operate on the data generated by this one.  If this tool could output a list of tile locations, a secondary tool could snarf that and recover topological information pretty easily. Of course, if you're doing that, you could almost just recover all the information you wanted from the generated SVG.  (Well, maybe convert the SVG into a flat Postscript file first, and then parse that. I've actually done that for a few small parts of this project.)

**Comment by isohedral** [comment]
In the latest update I included a "Save Matrices" button. It saves a text file giving the label and matrix for each hat in the patch. The matrix is given as six numbers, namely the top two lines of a 3x3 2D affine transformation matrix.  Call it a six-element array `T`. `T[2]` and `T[5]` give the translation of the hat. `atan2( T[3], T[0] )` should give the rotation angle. The determinant `T[0]*T[4] - T[1]*T[3]` is negative when the matrix includes a reflection.

**Comment by nealmcb** [comment]
Thank you - very clean and compact!
And I have also found the link you posted to [Simon Tatham's essay](https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/aperiodic-tilings/) to be even more relevant to my underlying curiosity around the trees of F metatiles. His [code](https://git.tartarus.org/?p=simon/puzzles.git) has a handy undocumented `--python` argument that produces a patch of hats in this format:
```
$ hat-test --python 4 3
hat('H', 2, 0, [(12,0), (14,0), (14,2), (13,3), (14,6), (13,9), (12,8), (11,9), (10,6), (8,6), (8,4), (9,3), (10,2), (11,3)])
hat('H', 3, 2, [(11,9), (12,8), (13,9), (14,10), (14,12), (12,12), (11,15), (10,14), (9,15), (8,12), (9,9), (8,8), (8,6), (10,6)])
hat('H', 1, 4, [(4,12), (3,9), (4,8), (5,9), (6,6), (8,6), (8,8), (9,9), (8,12), (9,15), (8,16), (7,15), (6,14), (6,12)])
```

I've been fleshing our some code to implement the `hat` function and color distinct tree segments in different colors, as I did above, in a more automated way.

**Comment by isohedral** [comment]
Nice!! I had also looked over Simon's code, which is really well engineered and should be quite usable outside the context of puzzles. But I didn't notice the `--python` option—that's an excellent find, and I suspect that in the end it's a better tool than `hatviz` for what you're trying to accomplish. Have fun!
